import JSZip from 'jszip';
import { AuditResult } from '../types';

export const downloadAuditPackage = async (
  creativeBase64: string,
  fixedImage: string | null,
  result: AuditResult
) => {
  const zip = new JSZip();

  // Helper to extract base64 data
  const getBase64Data = (dataUrl: string) => dataUrl.split(',')[1];

  try {
    // 1. Original Creative
    zip.file("original_creative.png", getBase64Data(creativeBase64), { base64: true });

    // 2. Fixed Creative (if applicable)
    if (fixedImage) {
      zip.file("fixed_creative.png", getBase64Data(fixedImage), { base64: true });
    }

    // 3. Audit Report (Text)
    const report = `
ADCHECK COMPLIANCE AUDIT REPORT
===============================
Date: ${new Date().toLocaleString()}

VERDICT
-------
Pass: ${result.pass ? 'YES' : 'NO'}

VIOLATIONS
----------
${result.violations.length > 0 ? result.violations.map((v, i) => `${i + 1}. ${v}`).join('\n') : 'None'}

CORRECTIVE INSTRUCTION
----------------------
${result.corrective_instruction || 'N/A'}

----------------------
Generated by AdCheck AI Auditor
    `.trim();

    zip.file("audit_report.txt", report);

    // Generate Zip
    const blob = await zip.generateAsync({ type: "blob" });

    // Download
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `adcheck_audit_${Date.now()}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Cleanup
    setTimeout(() => URL.revokeObjectURL(link.href), 100);
  } catch (error) {
    console.error("Failed to generate export package:", error);
    alert("Failed to generate download package.");
  }
};